### PR TITLE
Fix stat.time

### PR DESCRIPTION
**Pull request by zarda**
To fix issue #87 .
Correct time unit to be ms.
Tested well on Ubuntu 18.

### CODE REVIEW

**Comment by zarda** [comment]
Usage.cpu still be 0 on Linux and MS windows.

**Comment by soyuka** [comment]
I'll fix the cs-related errors in another pull request

**Comment by paulfitz** [comment]
@soyuka thanks for the handy library! Wondering if you plan on merging this soon? I think I'm hitting this problem also.

**Comment by soyuka** [comment]
available in 2.0.18

**Pull request merged**
