### PR TITLE
Don't use cpus count to compute pcpu revert #59

### PR DESCRIPTION
**Pull request by soyuka**
#58 
https://github.com/Unitech/pm2/issues/3708

### CODE REVIEW

**Comment by simonepri** [comment]
You need to remove:
https://github.com/soyuka/pidusage/blob/master/test/ps.js#L45
https://github.com/soyuka/pidusage/blob/master/test/ps.js#L110

**Comment by simonepri** [comment]
How these behave on multi-threaded process? 
https://github.com/soyuka/pidusage/blob/master/lib/procfile.js#L48
https://github.com/soyuka/pidusage/blob/master/lib/wmic.js#L105

**Comment by soyuka** [comment]
> You need to remove:
https://github.com/soyuka/pidusage/blob/master/test/ps.js#L45
https://github.com/soyuka/pidusage/blob/master/test/ps.js#L110

Not really, let's keep them for later they're not used anymore.

> How these behave on multi-threaded process?
https://github.com/soyuka/pidusage/blob/master/lib/procfile.js#L48
https://github.com/soyuka/pidusage/blob/master/lib/wmic.js#L105

I'll find time to investigate on this. First guess is joins what you said earlier - nothing is telling us if the process is using more then 1 core. This means that we can't really divide by the number of cores... 
I don't know which value we can use, especially that `utime/stime` values that we're using are not telling us anything about cores and I'm really not sure that it's easier as `totaltime / cpus number` in the end.

**Comment by simonepri** [comment]
"nothing is telling us if the process is using more then 1 core"
Actually that is not completely true.

Let's assume that you do 2 measurements in **t1** and **t2**
If the cpu time used by the process is greater than **t2-t1** then you must have used more than 1 cpu.

Those are supposition, I'm not actually aware on how the utime /stime are actually counted

**Comment by simonepri** [comment]
```js
// process usage since last call in seconds
var total = (stat.stime - (hst.stime || 0) + stat.utime - (hst.utime || 0) + childrens) / cpuInfo.clockTick
// time elapsed between calls in seconds
var seconds = Math.abs(hst.uptime !== undefined ? stat.uptime - hst.uptime : stat.start - stat.uptime)
```
If my suppositions are true, then `total / seconds` may be greater than 1 and our code just works as is🤓
We just need to remove these lines:
https://github.com/soyuka/pidusage/blob/master/lib/procfile.js#L53
https://github.com/soyuka/pidusage/blob/master/lib/wmic.js#L110

**Comment by simonepri** [comment]
Probably we need to get rid of `Math.min` everywhere.

**Comment by soyuka** [comment]
Yes, my guess is that you're probably right! 

Anyway, it's always tricky to represent CPU usage because it's hard to tell what it actually is IMO.  The current value is "representative" without being perfectly exact. 
We definitely need to add more data in the results, maybe with something closer to the truth :D.

I'm merging as-is for now!

**Pull request merged**
