### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by soyuka**
#13 #14 ping @crystaldust

### CODE REVIEW

**Comment by soyuka** [comment]
Continuing #14 discussion

> Hi, I tried it in a virtual machine(virtual box, Windows7 Pro SP1 32bits), and it works. Would you try this method below and dig more info?
The method:
start -> run -> wbemtest -> connect, keep the Namespace 'root\cimv2', then 'Enum Instances', input "Win32_PerfFormattedData_PerfProc_Process", and see what it tells.


It says that the class can not be found. Weird, should I install something to get this to work?

**Comment by crystaldust** [comment]
I googled it a bit and found some threads that might be helpful, would you take a look at them?

http://blogs.technet.com/b/askperf/archive/2009/04/13/wmi-rebuilding-the-wmi-repository.aspx
https://madvirtualizer.wordpress.com/2014/02/05/are-you-sure-you-need-to-rebuild-the-wmi-repository/

And also check the registry item:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\PerfProc\Performance\Disable Performance Counters, of which the type is DWORD, is set to 0

**Comment by soyuka** [comment]
Hmm, so on my computer I have no such `Disable` in the registry :/. The wmi repository looks fine from both links you send over.

I checked on another Windows that the `Win32_PerfFormattedData_PerfProc_Process` instance exist, and it does. I think my computer may have an issue with this...

I'll merge and release soon, thanks for taking the time to answer my questions :).

**Comment by crystaldust** [comment]
U'r welcome, happy to make contributions : )

**Pull request merged**
