### PR TITLE
Fix array when pid has not been found

### PR DESCRIPTION
**Pull request by soyuka**
@simonepri how can I reproduce your date issue?

### CODE REVIEW

**Comment by simonepri** [comment]
I'm tring to do a PR fixing it

**Comment by soyuka** [comment]
Nice thanks, this looks like a darwin only issue and I've no OS X :|

**Comment by soyuka** [comment]
Looks like `time` is a number on osx:

```
time
accumulated cpu time, user + system (alias cputime)
```

But I don't know if those are seconds

**Comment by simonepri** [comment]
@soyuka Sorry for the delay.
I will submit the PR within the day.
I've refactored the whole code these are the results on my machine now:

image

**Pull request merged**
